#!/usr/bin/env python3
"""Reproduce the pinned Arc-Admin before state without running project commands."""

import argparse
from datetime import datetime
import hashlib
import json
from pathlib import Path
import tomllib

BASELINE = Path(__file__).resolve().parent
COMMIT = "9982ed556eaf997910824d7b682946147c81a16a"


def seconds(start, end):
    return int((datetime.fromisoformat(end) - datetime.fromisoformat(start)).total_seconds())


def reproduce(root=BASELINE):
    manifest = json.loads((root / "source-manifest.json").read_text())
    assert manifest["commit"] == COMMIT, "before-state commit changed"
    sources = {}
    for entry in manifest["files"]:
        raw = (root / entry["snapshot"]).read_bytes()
        assert hashlib.sha256(raw).hexdigest() == entry["sha256"], entry["path"]
        blob = b"blob " + str(len(raw)).encode() + b"\0" + raw
        assert hashlib.sha1(blob).hexdigest() == entry["sha"], entry["path"]
        sources[entry["path"]] = raw.decode()
    flow = tomllib.loads(sources[".arc-flow/flow.toml"])
    steps = flow["steps"]
    required = flow["policy"]["required_steps"]
    inventory = {
        "repository": manifest["repository"], "commit": COMMIT,
        "flow": flow,
        "audit": tomllib.loads(sources["codex-audit-pipeline/.codex/audit.toml"]),
        "secrets": tomllib.loads(sources["codex-audit-pipeline/.codex/secrets.toml"]),
        "components": sorted({s["component"] for s in steps}),
        "always_blocking_prelude": ["secret scan", "architecture audit"],
        "blocking_when_selected": [s["id"] for s in steps],
        "blocking_beyond_policy_list": [s["id"] for s in steps if s["id"] not in required],
        "profile_steps": {p: [s["id"] for s in steps if p in s["profiles"]]
                          for p in sorted({p for s in steps for p in s["profiles"]})},
        "ownership": {s["id"]: "project-owned validation; generic command hook"
                      for s in steps},
    }
    table = ["# Frozen execution steps", "", "Generated by `python3 docs/dogfood/arc-admin/reproduce.py --write`.", "",
             "Every row blocks when selected. P denotes membership in `policy.required_steps`.", "",
             "| Step | P | Profiles | Timeout seconds / override | Parser / service | Command (cwd) | Log |",
             "| --- | --- | --- | --- | --- | --- | --- |"]
    for s in steps:
        timeout = str(s["timeout_secs"]) + (" / " + s["timeout_env"] if "timeout_env" in s else "")
        integration = " / ".join([s.get("parser", "—"), ", ".join(s.get("services", [])) or "—"])
        command = " ".join([s["program"], *s["args"]])
        table.append(f"| {s['id']} | {'yes' if s['id'] in required else 'no'} | {', '.join(s['profiles'])} | {timeout} | {integration} | `{command}` (`{s['cwd']}`) | `{s['log']}` |")
    capture = json.loads((root / "ci-capture.json").read_text())
    costs = []
    for sample in capture["samples"]:
        run = sample["run"]
        assert sample["jobs_status"] == sample["artifacts_status"] == 200
        assert sample["jobs_total"] == len(sample["jobs"]), "paginated jobs missing"
        assert sample["artifacts_total"] == len(sample["artifacts"]), "paginated artifacts missing"
        jobs = []
        for job in sample["jobs"]:
            # Skipped jobs can have reversed timestamps; they consumed no execution.
            skipped = job["conclusion"] == "skipped"
            duration = 0 if skipped else seconds(job["started_at"], job["completed_at"])
            assert duration >= 0
            buckets = {"project_commands": 0, "scope": 0, "artifacts": 0,
                       "setup_and_teardown": 0}
            for step in job["steps"]:
                if step["conclusion"] == "skipped":
                    continue
                name = step["name"]
                category = "setup_and_teardown"
                if name.startswith(("Verify", "Run backend", "Run frontend", "Audit", "Check licenses", "Build production", "Scan high", "Generate SPDX")):
                    category = "project_commands"
                elif name == "Detect verification scope":
                    category = "scope"
                elif name.startswith("Upload"):
                    category = "artifacts"
                buckets[category] += seconds(step["started_at"], step["completed_at"])
            jobs.append({"name": job["name"], "conclusion": job["conclusion"],
                         "labels": job["labels"], "runner_seconds": duration,
                         "step_seconds": buckets,
                         "job_overhead_seconds": duration - sum(buckets.values())})
        active = [j for j in sample["jobs"] if j["conclusion"] != "skipped"]
        costs.append({"run_id": run["id"], "url": run["html_url"], "name": run["name"],
                      "head_sha": run["head_sha"], "conclusion": run["conclusion"],
                      "created_to_updated_seconds": seconds(run["created_at"], run["updated_at"]),
                      "first_job_wait_seconds": seconds(run["created_at"], min(j["started_at"] for j in active)) if active else None,
                      "execution_span_seconds": seconds(min(j["started_at"] for j in active), max(j["completed_at"] for j in active)) if active else 0,
                      "runner_seconds": sum(j["runner_seconds"] for j in jobs),
                      "jobs": jobs, "artifacts": sample["artifacts"],
                      "monetary_cost": None,
                      "measurement_and_parsing_seconds": None})
    return {"inventory.json": json.dumps(inventory, indent=2) + "\n",
            "steps.md": "\n".join(table) + "\n",
            "cost-summary.json": json.dumps(costs, indent=2) + "\n"}


def check(root=BASELINE):
    for name, content in reproduce(root).items():
        assert (root / name).read_text() == content, f"stale baseline: {name}"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate reviewed snapshot summaries")
    args = parser.parse_args()
    if args.write:
        for name, content in reproduce().items():
            (BASELINE / name).write_text(content)
    else:
        check()
    print("Arc-Admin pinned baseline: PASS")
